apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-ops-view
  namespace: kube-ops-view
  annotations:
    tailscale.com/tags: "tag:k8s,tag:k8s-m720q"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kube-ops-view
      port:
        number: 80
  tls:
    - hosts:
        - m720q-kov
