apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:FF0KFahmA5fOhjeYorAGevna2xMD7Lec8OeTNArUI3/9iLBz4BPIBw==,iv:FIc2aPrupm+3SvqoRz76jK95jXheJohbUIPN1+gsDr0=,tag:7QDPOmt92zdvgNVtXlDGXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTWdBOFQ4QUFGVE1YOWFF
            U2RTNklRZU15djlHNWwvMjhFRWxYbzIzVEF3CmJEWHI3bndYa3U4YU9rR3VpQk1U
            OUVqdnJ0b1g0Wks5dndHOE1kNEtkamMKLS0tIFRPWEQySWg5M21yYlF4UytFelFT
            eVJWNDFJT3RETDZpSG9vMFQrWjFVa0UKqkQk9Z9SxlcJbp9gRngUgXmSSzdqTID/
            joC0iwy1j1DaOjqd9o2n6TfAgNNPrGGi9wQR+/Zg8YPV1KYNJm28AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wkvrmnp8y9ce6sv43ydfy0d5r37r2vp0hcl7xsvg0qvxz6sarcwqk4cc6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanJvZGcyTnROa2p6MjRk
            YVh3S0F0VGR1Z0hYM05WeFpXN3gvMWVpL3hjCk02VnBzaTV2bElrZXcwTGJpYkdJ
            TDlNQTBPcHhFajZ2eStwZGV0Q3dIV3cKLS0tIFN3a0p5Visxdm1Wc1Y3cGlMUXJw
            ODNuMlA0eCtRUGZBZzlUUjRlOUlSZGcK1Y0z2pLBcR0L6sKJsCPxhMtijx5T9mVr
            Z6YlZfqm7/OZXmDyG2O9PfRUU+v07WvmG/2ArzgaF6L8Zobh48ct1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T20:43:23Z"
    mac: ENC[AES256_GCM,data:njLX4XLFuJwFLFATA/gbiUPjrsLzLH/0alF7pz4Mf8hBhZBeYYc+EVd2MuNrWfSJGZoHQYSvEhXi5S30zm/AuZHUFPIRcqlfuJlZhSWVD3ZJ2kzw3DgVCtU0aKplHZZOhfquWmNsHzm717NhHgP5wyTuzTIp+DWyjweYtpnMqUg=,iv:xmqeahKeLHBJwPn+rkvYKf/o2EH08U14xHHT+kTuNr0=,tag:a63QNt4zMFfpdu2x1fKGnw==,type:str]
    version: 3.13.3
