apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi-rbd
stringData:
    userID: ENC[AES256_GCM,data:e2FAtLzBhNI=,iv:Yol/ottp0gFlYbdnbcnaG5WXA+cHjhIwIFnqXxQzh8Y=,tag:BhglJ52RSj+BnHAXOuhdyA==,type:str]
    userKey: ENC[AES256_GCM,data:AXOKvrhhz4c2k89ZIji9/l831rS284v1z6r0BpwVGUHY4yzqhNEw2g==,iv:lebb9QYRJ1DxkOFbRITo2aCYPeSLlw5DFqvKTPKlu48=,tag:ikLuAXcrj0b3ckgWYqN6sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV1daWlF4cHpRUnpuVjJB
            YzdnOU1kQWY0VFNaNzVOdVNxelVZejVrL0JRCkhQMVIwYnVXZXRGVVlOdThIV3Rw
            SGFIcHBrS3V3ZjVoWW9iVU5pbmwzdEkKLS0tIE84eG9vcTVmSnBHaFR6M0lYQ2tx
            YlBMUm5wcVY2dDVjNGNJTEpxUTN3eE0KzmoMa4wSSC+j0Y2JKi5eiyhQzJ0WGk8d
            dJ8JEL+1KInAIQnX9E8qdIWvGRTRBlcV8UOQZT9h0LDn5L9hFAPtcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wkvrmnp8y9ce6sv43ydfy0d5r37r2vp0hcl7xsvg0qvxz6sarcwqk4cc6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWi9MQUdnR0pObGdRKzFL
            aHhRdno1OUxDNE8zV1hUbkpBQlp4ZGhpSGxBCmJuVWVKRTZnZFo2R2JvUDhod3RE
            UDZPMTR0TC9KTUg5djMwTkhCWVZucDgKLS0tIEdqaE5FK3dWdm0xVVNnWGRuMUQ0
            V1lwWkVKQzloNFI3dkcwVWFTSzBiVlEKEhyccOXxDLpTeGNergW9W22eJCN6QyyW
            P31r1gGgdEwW/olox6VQir5fOfZXpmfaglw+49c3o4OZdmW13LN7hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T15:56:52Z"
    mac: ENC[AES256_GCM,data:evtxp/zimZw4wR83T3nFnB3/ApciWKQDcvOXg78OGoUsbs+tm5yMN/VgRqYuYR/YD2fjw4Nvdj4svX82I1ifV5mnu4zOpX0xY+4NvGTJhU4O0D4oR8ZMbtpCRG0ThLNE4mvJW9y/kw+mk8OU18twzl1BuyMSj6f8iszaT4i6IkE=,iv:DJ8RjKYdncSEeSHuA4MeAKNFPzqw4C5ibEnLYzL3CkE=,tag:QKC9GjOSVJvvz0D8UwO7lQ==,type:str]
    version: 3.13.3
