apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:a/cslBCKv/1xeXC3s4NBqfq/WfwWCg5qd+cIi8YJnYM=,iv:cuXJTyGXID38AaNMvXDSeablXGOtq+6xfcaA9YnRR40=,tag:whoJOfwKEp95EljywlMpIA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:p6lg76RuZb26QkwEQDbaiHMWckMjGBcYHg+Zh/s9xGDklEnO0achNk/cc3pIaJCh5IWJhDDxJgI6KRnSD0IIDg==,iv:7vMqWsITjHDMEVNBv8nEZpnlzItqbvCru7b6XURg39o=,tag:asYtYziP7lQMflNeim41MA==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:mBT2wThMjp0FM0p950kO7YMV8n0sQw==,iv:Ag8mvC0wckzEdzCKatOpA98/APGw08sJNKt2x8kJimY=,tag:l4/33vzd4ouQ6DpbZnGqEA==,type:str]
    OIDC_CALLBACK_URL: ENC[AES256_GCM,data:NSQ+gMQ+4eXj2A3m+AOcm3WTv+m1EcmyHM8X7CyjPg8tPBjOOU/UYngDRZUiRA==,iv:Cx6iG/Us0zQInUabtvmkyL71FuQa6wRCB/4vqVf6OlE=,tag:m41HTelXZbEoIuqFG4iwCA==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:C1KVFd2aCVtImzQdKAO2aWI9x1w=,iv:flXQe/0F7ou1QX3QBdS5iLKYsEcTHk1aydHbSEgOlA4=,tag:/wUwZp4V3/60iypcnnGtWQ==,type:str]
    OIDC_USE_PKCE: ENC[AES256_GCM,data:heIuQQ==,iv:7YhpkOvXbVY6KyC+wKwUCXJI+I86VKt7xmhhcDapJU8=,tag:bnRJ/4+R6F3gRu2RE56cJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReHFxZktmQTlBYk1sQTh4
            U3dzMHNrUzVwdSt1azhyZFdUamRvQTdWZEJRCnhmOWxmdmgyZ0FhUmpWa0FkN1li
            cFFqbEtSckgrcHJjZDE5Z0s3NjJqZ0UKLS0tIEVYWTUyWHV1VzhhV3FEUnBmczl2
            dGEvZ2pDdDVTT2tNeHB6SGV3d0t2bFEKVZqhntavzRS2HgziTsIVYNh2GEd/frXm
            drVNFNv0QDxth0SKq5fO+A1KAFu3UhTi35bYHux7YSiCEv4n/RG/Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wkvrmnp8y9ce6sv43ydfy0d5r37r2vp0hcl7xsvg0qvxz6sarcwqk4cc6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUTdQVTYreXprdFBBUFVX
            dWZDdjA1ckQvWEtlUUdlaWhZMVJrT04xdFNnCkw1eXVGY2JmUGU2R29laWs2cnY2
            Qmg2QlV1Q05lSVNibUZZdEswZ2ZaRFkKLS0tIEd0cTBQSjJTTUlqVTlVM3VZUmxx
            WkZyd21oSnFuZHMzeVp4MGpzUGNycU0KAvgKM/eBk1WKEdSeX4AEZYfVLAelV+2f
            62yYP/XX46dKTIrZENpo7oHAZoA58j02zZK0tX63/hM3LdqNLSKpfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:43:16Z"
    mac: ENC[AES256_GCM,data:2InaTiwGKkFER1pAaCehWVEXnIHGnRzD//q2PmGJNcazoBVq7ivT8pjCiQ5LUHS5f2z7aV8EYeMR0N9wa/Th0LY5h/1Uw6+PlctdTjs9BAoOnAbklpwzBViKqHfwDA8XFoLSk2ESbVTYzUSV/+mbuA8jvYlaRKp8MJ91CkX0ip4=,iv:7gj5Gt/HPyN8RCUnQKSPE+FcBx8iQaud75GzBmzt3KA=,tag:YcgCPqSfp4mRfx8c0PVy7A==,type:str]
    version: 3.13.3
