apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.json
  - cilium-repository.json
  - cilium-release.json
  - ceph-csi-repository.json
  - ceph-secret.sops.yaml
  - ceph-csi-rbd-release.json
  - tailscale-namespace.json
  - tailscale-repository.json
  - tailscale-secret.sops.yaml
  - tailscale-release.json
