apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.json
  - cilium-repository.json
  - cilium-release.json
  - ceph-csi-repository.json
  - ceph-secret.sops.yaml
  - ceph-csi-rbd-release.json
  - tailscale-namespace.json
  - tailscale-repository.json
  - tailscale-secret.sops.yaml
  - tailscale-release.json
  - headlamp-namespace.json
  - headlamp-repository.json
  - headlamp-secret.sops.yaml
  - headlamp-release.json
  - headlamp-ingress.json
  - headlamp-rbac.json
  - monitoring-namespace.json
  - prometheus-repository.json
  - grafana-secret.sops.yaml
  - monitoring-release.json
  - grafana-ingress.json
  - grafana-dashboard.json
  - traefik-namespace.json
  - traefik-repository.json
  - traefik-release.json
  - cert-manager-namespace.json
  - cert-manager-repository.json
  - cert-manager-release.json
  - ingress-sync.json
