apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:J8DwHIfFn5oz5Gxyts6DxAs=,iv:3B7TBXCbK3lfKmLvLKP0DK0Jsc2fF0fglrs5GJ8sLa4=,tag:0LCDFonE2Xb2WqYW6obdEg==,type:str]
    client_secret: ENC[AES256_GCM,data:Z80bTRNld72GPPl+dltZShn/MhLN4eVBLu+mbMW8BWmvjiFSm2pvJs3hf2WzuBSr9cm5KaRCA/5AtgdOu23KFw==,iv:jrNs1UGoehreVQFjJ5iGpoetNlBkJbNWk2XefTjjz8k=,tag:YmG36PrN30eAESTA7yHSpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVU5UNEVmRHB3UkgyM01G
            ZHhjMW5nQXdEYTdXSGtUc2pSVHBSRmRnMFcwCmxxSC9LRnBzVlIxdVo2Qys4c2kx
            YkdIYkF4RVFUWkdFc2dzUkZZZ3N6cncKLS0tIFNhU1hTb2V0dVl1OTJrcU5CRnlP
            b0dCb1BPRTBmdkw3TzdFR3RwM0VCcjQK5j54oR88V7ycji9NXmzG8X5BaC9mxg5w
            1/I8o83Dn2vxP6XxZYiTyY0HJJ7PMIOIUrWRHNGHc3QrgfdLudz/7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wkvrmnp8y9ce6sv43ydfy0d5r37r2vp0hcl7xsvg0qvxz6sarcwqk4cc6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiekxuN2VJOXV6emhMem8v
            U2U3WElGRVFDbTZ6NTdiZkQ1Y0xLOHhibG1NCmhtT3VVQTgwcmdrSmN3UFZpL0lY
            SUpJSld5NDdZUmQxUFBVUGxkb1Nha0EKLS0tIGFVQmFZcnRoOXNCVW1XbEFnMWJv
            d1dud2M1WlM1MC9zUXdBMWdFZUFhc00KpegR48EZ/nBZ8axppXXEbQKhD2q4Zfus
            HJtyaW9wCAT+E7Rlj7Shn1xUNzfulfhp3Vhan+QUvmq76goKfnnmuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:32:30Z"
    mac: ENC[AES256_GCM,data:y6jjBFtTi25IWNXIUSS1S7YnAXQTcrrf30h7DIUaDwvBkBG90B9fpkX8SwrYpKDhPLDZutFPDR5T12GxqKK3/cuFKPYvZDSHYa6UBDuuWEWuqIH/tteypRS44x1TKUdZbClX4eNustHmhTsTAG/r6+7piwEBm62KzgvUzVq/MfU=,iv:nH9XKheg//BA7QAiHcoxdymsysD+5v/bGGyBNEQuMgM=,tag:bIqDjV5mclDI29QRfZrFTA==,type:str]
    version: 3.13.3
