apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - infrastructure-core.yaml
  - api-proxy.yaml
  - infrastructure.yaml
  - rook-ceph-operator.yaml
  - rook-ceph-cluster.yaml
  - smokeping.yaml
  - jellyfin.yaml
  - kube-ops-view.yaml
